### ISSUE TITLE
AttributeError: 'UNet' object has no attribute 'loss_functions'

### ISSUE THREAD

**Issue by vaibhavbahel** [perslev/MultiPlanarUNet#11]
Epoch 1/500
417/417 [==============================] - ETA: 0s - loss: 0.1224 - sparse_categorical_accuracy: 0.9805'UNet' object has no attribute 'loss_functions'
Traceback (most recent call last):
  File "/usr/local/bin/mp", line 8, in <module>
    sys.exit(entry_func())
  File "/usr/local/lib/python3.6/dist-packages/mpunet/bin/mp.py", line 55, in entry_func
    mod.entry_func(parsed.args)
  File "/usr/local/lib/python3.6/dist-packages/mpunet/bin/train.py", line 390, in entry_func
    raise e
  File "/usr/local/lib/python3.6/dist-packages/mpunet/bin/train.py", line 386, in entry_func
    run(project_dir=project_dir, gpu_mon=gpu_mon, logger=logger, args=args)
  File "/usr/local/lib/python3.6/dist-packages/mpunet/bin/train.py", line 349, in run
    hparams=hparams, no_im=args.no_images, **hparams["fit"])
  File "/usr/local/lib/python3.6/dist-packages/mpunet/train/trainer.py", line 161, in fit
    raise e
  File "/usr/local/lib/python3.6/dist-packages/mpunet/train/trainer.py", line 147, in fit
    **fit_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mpunet/train/trainer.py", line 257, in _fit
    verbose=verbose
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 813, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/callbacks.py", line 365, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/usr/local/lib/python3.6/dist-packages/mpunet/callbacks/validation.py", line 263, in on_epoch_end
    class_wise_metrics, mean_batch_wise_metrics = self.evalaute()
  File "/usr/local/lib/python3.6/dist-packages/mpunet/callbacks/validation.py", line 145, in evalaute
    metrics = self.model.loss_functions + self.model.metrics
AttributeError: 'UNet' object has no attribute 'loss_functions'

**Comment by covasquezv** [comment]
Were you able to solve this issue? I'm facing the same one.

**Comment by christian-igel** [comment]
Hi,

Mathias, who has implemented MPUnet, is currently on vacation, so it may take some time to look into this issue.
Anyway, please send us details about your environment, TF version, Python version, OS, etc.

Best regards,
Christian 
--
Prof. Dr. habil. Christian Igel
Department of Computer Science
University of Copenhagen

Office address:
Room 1.2.20
Universitetsparken 1
DK-2100 København Ø

Mail address:
Universitetsparken 5
DK-2100 København Ø

Homepage: http://image.diku.dk/igel
Phone: (+45) 21849673

SCIENCE AI Centre: ai.ku.dk
DIKU Machine Learning Section: http://di.ku.dk/ml

**Comment by covasquezv** [comment]
Hi Christian, thanks for replying. 

In my case, I'm using a p3.2xlarge AWS instance with the following details:
- Deep Learning AMI (Ubuntu 18.04) Version 30.0
-  CUDA 10.0
- Tensorflow-gpu 2.2.0
- Python 3.6

I've followed each one of the instructions, but in this line:
`mp train --num_GPUs=2   # Any number of GPUs (or 0)`

the following error arise after the first epoch is completed:

```
Epoch 1/500
1/1 [==============================] - ETA: 0s - sparse_categorical_accuracy: 0.9208 - loss: 0.2810'UNet' object has no attribute 'loss_functions'
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/bin/mp", line 11, in <module>
    load_entry_point('mpunet', 'console_scripts', 'mp')()
  File "/home/ubuntu/MultiPlanarUNet/mpunet/bin/mp.py", line 55, in entry_func
    mod.entry_func(parsed.args)
  File "/home/ubuntu/MultiPlanarUNet/mpunet/bin/train.py", line 390, in entry_func
    raise e
  File "/home/ubuntu/MultiPlanarUNet/mpunet/bin/train.py", line 386, in entry_func
    run(project_dir=project_dir, gpu_mon=gpu_mon, logger=logger, args=args)
  File "/home/ubuntu/MultiPlanarUNet/mpunet/bin/train.py", line 349, in run
    hparams=hparams, no_im=args.no_images, **hparams["fit"])
  File "/home/ubuntu/MultiPlanarUNet/mpunet/train/trainer.py", line 161, in fit
    raise e
  File "/home/ubuntu/MultiPlanarUNet/mpunet/train/trainer.py", line 147, in fit
    **fit_kwargs)
  File "/home/ubuntu/MultiPlanarUNet/mpunet/train/trainer.py", line 257, in _fit
    verbose=verbose
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 876, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py", line 365, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/ubuntu/MultiPlanarUNet/mpunet/callbacks/validation.py", line 263, in on_epoch_end
    class_wise_metrics, mean_batch_wise_metrics = self.evalaute()
  File "/home/ubuntu/MultiPlanarUNet/mpunet/callbacks/validation.py", line 145, in evalaute
    metrics = self.model.loss_functions + self.model.metrics
AttributeError: 'UNet' object has no attribute 'loss_functions'
```

**Comment by perslev** [comment]
Hi, thank you for your interest! Sorry for my late response. As Christian said, I have been on vacation over the last few weeks.

I was able to recreate this error on my system with TensorFlow 2.2. I have now updated the ```mpunet``` package to version ```0.2.6``` which should solve this issue. Please try to pull the latest repo from GitHub or install the new package with ```pip install mpunet==0.2.6```.

If you experience any issues please feel free to reach out again.

Cheers,
Mathias
