### ISSUE TITLE
Error when trying to train

### ISSUE THREAD

**Issue by Tooba-ts1700550** [perslev/MultiPlanarUNet#18]
Hello,

I keep getting this error when trying to train in colab. I followed the steps in the readme file. I am using the following commands:
```
!mp init_project --name my_project --data_dir Task04_Hippocampus
!mp train --project_dir=my_project --num_GPUs=2   # Any number of GPUs (or 0)

```
Output

```
--------------------------------------------------------------------------------
>>> Logged by: 'entry_func' in 'train.py'
Fitting model in path:
/content/my_project
--------------------------------------------------------------------------------
>>> Logged by: '__init__' in 'hparams.py'
YAML path:    /content/my_project/train_hparams.yaml
--------------------------------------------------------------------------------
>>> Logged by: 'log_version' in 'version_controller.py'
mpunet version: 0.2.11 (master, a46779c)
--------------------------------------------------------------------------------
>>> Logged by: 'set_value' in 'hparams.py'
Setting value '0.2.11' (type <class 'str'>) in subdir 'None' with name '__VERSION__'
Setting value 'master' (type <class 'str'>) in subdir 'None' with name '__BRANCH__'
Setting value 'a46779c' (type <class 'str'>) in subdir 'None' with name '__COMMIT__'
--------------------------------------------------------------------------------
>>> Logged by: 'save_current' in 'hparams.py'
Saving current YAML configuration to file:
 /content/my_project/train_hparams.yaml
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (numpy 1.19.5 (/usr/local/lib/python3.7/dist-packages), Requirement.parse('numpy<1.19.0,>=1.16.0'), {'tensorflow-gpu'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/mp", line 33, in <module>
    sys.exit(load_entry_point('mpunet', 'console_scripts', 'mp')())
  File "/content/MultiPlanarUNet/mpunet/bin/mp.py", line 55, in entry_func
    mod.entry_func(parsed.args)
  File "/content/MultiPlanarUNet/mpunet/bin/train.py", line 416, in entry_func
    raise e
  File "/content/MultiPlanarUNet/mpunet/bin/train.py", line 412, in entry_func
    run(project_dir=project_dir, gpu_mon=gpu_mon, logger=logger, args=args)
  File "/content/MultiPlanarUNet/mpunet/bin/train.py", line 344, in run
    args=args)
  File "/content/MultiPlanarUNet/mpunet/bin/train.py", line 250, in get_data_sequences
    from mpunet.preprocessing import get_preprocessing_func
  File "/content/MultiPlanarUNet/mpunet/preprocessing/__init__.py", line 1, in <module>
    from .scaling import apply_scaling, get_scaler
  File "/content/MultiPlanarUNet/mpunet/preprocessing/scaling.py", line 1, in <module>
    import sklearn.preprocessing as preprocessing
  File "/usr/local/lib/python3.7/dist-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/usr/local/lib/python3.7/dist-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/usr/local/lib/python3.7/dist-packages/sklearn/utils/__init__.py", line 23, in <module>
    from .class_weight import compute_class_weight, compute_sample_weight
  File "/usr/local/lib/python3.7/dist-packages/sklearn/utils/class_weight.py", line 7, in <module>
    from .validation import _deprecate_positional_args
  File "/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py", line 26, in <module>
    from .fixes import _object_dtype_isnan, parse_version
  File "/usr/local/lib/python3.7/dist-packages/sklearn/utils/fixes.py", line 28, in <module>
    from pkg_resources import parse_version  # type: ignore
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 3242, in <module>
    @_call_aside
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 570, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 583, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (numpy 1.19.5 (/usr/local/lib/python3.7/dist-packages), Requirement.parse('numpy<1.19.0,>=1.16.0'), {'tensorflow-gpu'})
```

**Comment by perslev** [comment]
Hi,

It seems your version of TensorFlow and numpy do not match. Could you please try and reinstall mpunet with `pip install --upgrade mpunet` and see if that fixes your issue? Otherwise please send me the output of `pip freeze`.

Cheers,
Mathias
