### ISSUE TITLE
not understand positional argument dim

### ISSUE THREAD

**Issue by poorneshwaran** [perslev/MultiPlanarUNet#2]
I got error while training. i.e(mp train --num_GPUs=1) like __init__ one positional argument :: dim

Traceback (most recent call last):
  File "/home/poornesh/.conda/envs/tensor14/bin/mp", line 11, in <module>
    load_entry_point('MultiPlanarUNet', 'console_scripts', 'mp')()
  File "/home/poornesh/my-projects/MultiPlanarUNet/MultiPlanarUNet/bin/mp.py", line 55, in entry_func
    mod.entry_func(parsed.args)
  File "/home/poornesh/my-projects/MultiPlanarUNet/MultiPlanarUNet/bin/train.py", line 339, in entry_func
    raise e
  File "/home/poornesh/my-projects/MultiPlanarUNet/MultiPlanarUNet/bin/train.py", line 335, in entry_func
    run(project_dir=project_dir, gpu_mon=gpu_mon, logger=logger, args=args)
  File "/home/poornesh/my-projects/MultiPlanarUNet/MultiPlanarUNet/bin/train.py", line 264, in run
    args=args)
  File "/home/poornesh/my-projects/MultiPlanarUNet/MultiPlanarUNet/bin/train.py", line 171, in get_data_sequences
    base_path=project_dir)
  File "/home/poornesh/my-projects/MultiPlanarUNet/MultiPlanarUNet/preprocessing/data_preparation_funcs.py", line 194, in prepare_for_3d_unet
    **hparams["fit"])
  File "/home/poornesh/my-projects/MultiPlanarUNet/MultiPlanarUNet/image/image_pair_loader.py", line 470, in get_sequencer
    **kwargs)
  File "/home/poornesh/my-projects/MultiPlanarUNet/MultiPlanarUNet/sequences/isotrophic_live_view_sequence_3d.py", line 10, in __init__
    super().__init__(image_pair_loader, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'dim'

**Comment by perslev** [comment]
Hi,

Could you please paste the content of your ‘train_hparams.yaml’ file? (feel free to remove any information you are not willing to share)

Are you trying to train a multi-planar u-net or 3D u-net?

**Comment by poorneshwaran** [comment]
Hi,

Here, I attached train_hparam_file. I trying to do 3D u-net.

[train_hparams.txt](https://github.com/perslev/MultiPlanarUNet/files/3638564/train_hparams.txt)

**Comment by perslev** [comment]
Hi, thanks!

Could you please pull the latest repo, checkout on the v0.2.2 branch and check if it works for you now? I would suggest you initialise a new project folder/parameter file with mp init_project after updating as minor changes have been made.

Cheers
Mathias
