### ISSUE TITLE
Predicting a 3D-Unet instead of a fusion-model ?

### ISSUE THREAD

**Issue by basile753** [perslev/MultiPlanarUNet#35]
Hi again,

I would like to compare the prediction results of the fusion model trained on my data with the result of a 3D Unet prediction. 
Is there any way to perform a 3DUnet prediction using your module ? I tried to use the predict_3D script even though I am not sure it was made for that purpose, and I got this error while everything works perfectly when I predict with the fusion model : 

UNet Model Summary
---------------------------------
Image rows:        512
Image cols:        512
Image channels:    1
N classes:         10
CF factor:         2.000
Depth:             4
l2 reg:            False
Padding:           same
Conv activation:   relu
Out activation:    softmax
Receptive field:   [155 155]
N params:          62062005
Output:            Tensor("conv2d/truediv:0", shape=(None, 512, 512, 10), dtype=float32)
Crop:              None

[*] Running on: 43
Traceback (most recent call last):
  File "../.venv37/lib/python3.7/site-packages/mpunet/bin/mp.py", line 59, in <module>
    entry_func()
  File "../.venv37/lib/python3.7/site-packages/mpunet/bin/mp.py", line 55, in entry_func
    mod.entry_func(parsed.args)
  File "/container/.venv37/lib/python3.7/site-packages/mpunet/bin/predict_3D.py", line 188, in entry_func
    N_extra=N_extra)
  File "/container/.venv37/lib/python3.7/site-packages/mpunet/utils/fusion/fuse_and_predict.py", line 175, in predict_3D_patches
    d = patches.dim
AttributeError: 'IsotrophicLiveViewSequence2D' object has no attribute 'dim'

Thx you guys.
Antoine.

**Comment by basile753** [comment]
Sorry this is just a misunderstanding from my side, I figured out I have to train a 3D-Unet model instead of a multiplanar-Unet based on a 2D-Unet in order to perform 3D-Unet predictions.

**Comment by basile753** [comment]
Sorry this is just a misunderstanding from my side, I didn't get the difference between a 2D-Unet and a 3D-Unet model, so I figured out that I could not perform a 3D-Unet prediction from a Multiplanar-Unet based on a 2D-Unet.
