### ISSUE TITLE
Clallbacks: Cannot feed value of shape (16, 128, 128, 1) for Tensor 'conv2d/truediv:0', which has shape '(?, 128, 128, 3)'

### ISSUE THREAD

**Issue by htt1994** [perslev/MultiPlanarUNet#4]
The project is much beneficial for me! Howeverm I got an error when traning at the code (outs = sess.run(tensors, feed_dict=ins)) in the file callbacks.py. The detail is following: 

  1/157 [..............................] - ETA: 29:39 - loss: 0.17492019-10-28 20:54:58.429846: I tensorflow/core/platform/default/device_tracer.cc:641] Collecting 1361 kernel records, 15 memcpy records.
156/157 [============================>.] - ETA: 0s - loss: 0.0912<class 'list'>
<class 'dict'>
self.model.total_loss: Tensor("loss_1/mul:0", shape=(), dtype=float32)
metrics_tensors: {}
self.model.outputs: [<tf.Tensor 'conv2d/truediv:0' shape=(?, 128, 128, 3) dtype=float32>]

W1028 20:55:51.747634 140053831063296 deprecation_wrapper.py:119] From /home/taoh/Project/DeepLearning/Examples/AwesomeExLearning/MultiPlanarUNet-master/MultiPlanarUNet/callbacks/callbacks.py:334: The name tf.keras.backend.get_session is deprecated. Please use tf.compat.v1.keras.backend.get_session instead.

tensors:  [<tf.Tensor 'loss_1/mul:0' shape=() dtype=float32>, {}, <tf.Tensor 'conv2d/truediv:0' shape=(?, 128, 128, 3) dtype=float32>]
Cannot feed value of shape (16, 128, 128, 1) for Tensor 'conv2d/truediv:0', which has shape '(?, 128, 128, 3)'
Traceback (most recent call last):
  File "/home/taoh/.vscode/extensions/ms-python.python-2019.9.34911/pythonFiles/ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "/home/taoh/.vscode/extensions/ms-python.python-2019.9.34911/pythonFiles/lib/python/ptvsd/__main__.py", line 432, in main
    run()
  File "/home/taoh/.vscode/extensions/ms-python.python-2019.9.34911/pythonFiles/lib/python/ptvsd/__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/home/taoh/anaconda3/envs/3Dircadb_Use_Unet/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/taoh/anaconda3/envs/3Dircadb_Use_Unet/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/taoh/anaconda3/envs/3Dircadb_Use_Unet/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/taoh/Project/DeepLearning/Examples/AwesomeExLearning/MultiPlanarUNet-master/MultiPlanarUNet/bin/train.py", line 344, in <module>
    entry_func()
  File "/home/taoh/Project/DeepLearning/Examples/AwesomeExLearning/MultiPlanarUNet-master/MultiPlanarUNet/bin/train.py", line 340, in entry_func
    raise e
  File "/home/taoh/Project/DeepLearning/Examples/AwesomeExLearning/MultiPlanarUNet-master/MultiPlanarUNet/bin/train.py", line 336, in entry_func
    run(project_dir=project_dir, gpu_mon=gpu_mon, logger=logger, args=args)
  File "/home/taoh/Project/DeepLearning/Examples/AwesomeExLearning/MultiPlanarUNet-master/MultiPlanarUNet/bin/train.py", line 290, in run
    hparams=hparams, no_im=args.no_images, **hparams["fit"])
  File "/home/taoh/Project/DeepLearning/Examples/AwesomeExLearning/MultiPlanarUNet-master/MultiPlanarUNet/train/trainer.py", line 122, in fit
    raise e
  File "/home/taoh/Project/DeepLearning/Examples/AwesomeExLearning/MultiPlanarUNet-master/MultiPlanarUNet/train/trainer.py", line 107, in fit
    val_ignore_class_zero)
  File "/home/taoh/Project/DeepLearning/Examples/AwesomeExLearning/MultiPlanarUNet-master/MultiPlanarUNet/train/trainer.py", line 215, in _fit_loop
    self.model.fit_generator(**fit_kwargs)
  File "/home/taoh/anaconda3/envs/3Dircadb_Use_Unet/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1433, in fit_generator
    steps_name='steps_per_epoch')
  File "/home/taoh/anaconda3/envs/3Dircadb_Use_Unet/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_generator.py", line 331, in model_iteration
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/taoh/anaconda3/envs/3Dircadb_Use_Unet/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py", line 311, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/taoh/Project/DeepLearning/Examples/AwesomeExLearning/MultiPlanarUNet-master/MultiPlanarUNet/callbacks/callbacks.py", line 428, in on_epoch_end
    TPs, relevant, selected, metrics = self.predict()
  File "/home/taoh/Project/DeepLearning/Examples/AwesomeExLearning/MultiPlanarUNet-master/MultiPlanarUNet/callbacks/callbacks.py", line 353, in predict
    outs = sess.run(tensors, feed_dict=ins)
  File "/home/taoh/anaconda3/envs/3Dircadb_Use_Unet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/taoh/anaconda3/envs/3Dircadb_Use_Unet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1149, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (16, 128, 128, 1) for Tensor 'conv2d/truediv:0', which has shape '(?, 128, 128, 3)'

**Comment by htt1994** [comment]
And the shape of X_ins is (?, 128, 128, 1), the shape of y_ins is (?, 128, 128, 3), and the shape of tensor is  (?, 128, 128, 3).

**Comment by htt1994** [comment]
The model is 
![image](https://user-images.githubusercontent.com/26806474/67687195-e9a71380-f9d2-11e9-9b14-80513448db12.png)

**Comment by perslev** [comment]
Hi!

Your y_ins should be of shape (?, 128, 128, 1) with each entry giving an integer-valued label. That is, values in {0, 1, 2} in your case for a 3-class problem. I would expect that you have your label maps stored in one-hot encoding (which would be normal, but not what is used here).

I am, however, surprised that you did not get a more appropriate error message - so perhaps this is not the error. I will look into it later this week as soon as I have more time.

If this does solve your issue let me know.

**Comment by htt1994** [comment]
Hi! Thank you for your reply! One thing I did not mention. I changed slightly your code in the callbacks.py
(y_ins = {in_tens: in_ for in_tens, in_ in zip(self.model.targets, y)}  --> y_ins = {in_tens: in_ for in_tens, in_ in zip(self.model.output, y)}),
due to the error "Unet object has no attribute 'targets' "

**Comment by htt1994** [comment]
And I tried doing binary segmentation. The error still exists.
![image](https://user-images.githubusercontent.com/26806474/67694412-3d6b2a00-f9de-11e9-81f8-4994b1958539.png)
So I think that one-hot encoding cannot solve the problem.

**Comment by htt1994** [comment]
Hi! I think I understand it. The problem is the code of callbacks.py:
'y_ins = {in_tens: in_ for in_tens, in_ in zip(self.model.targets, y)}', because I changed 'targets'(*,*,*,1) to 'outputs'(*,*,*,2) for binary segmentation. 
However, I still do not know the placeholder variable name of y_ins due to the error "Unet object has no attribute 'targets' ".

Best Wishes,
Tao H

**Comment by htt1994** [comment]
Hi! Maybe I solved the problem. I replaced 'targets' with '_targets' and it works. However, I do not known if it is true. 
![image](https://user-images.githubusercontent.com/26806474/67835133-33534380-fb24-11e9-94cd-9f67420a9da3.png)
Best Wishes,
Tao H

**Comment by perslev** [comment]
Hi,

Please update to the latest version (0.2.4) with TensorFlow >=2.0. If you still receive this error, please raise a new issue.

Cheers,
Mathias
