### ISSUE TITLE
Memory Error and Lack of GPU Usage

### ISSUE THREAD

**Issue by admshumar** [perslev/MultiPlanarUNet#6]
I'm attempting to train a Multi-planar U-Net with MPUNet 0.2.2 on an Ubuntu 18.04.3 LTS virtual machine with an Nvidia Tesla K80 GPU. Executing the command "mp train --force_GPU=true" produces a run through the training data:

> --------------------------------------------------------------------------------
> >>>Logged by: 'prepare_for_iso_live' in 'image_pair.py'
> OBS: Using 1 percentile BG value of [32768.0, 32768.0, 32768.0, -5.138273081684019e-06, 0.0]
> 1012_NSK47177
> --- shape:      [108 162 100   5]
> --- real shape: [108. 162. 100.]
> --- pixdim:     [1. 1. 1.]
> --------------------------------------------------------------------------------
> >>> Logged by: 'prepare_for_iso_live' in 'image_pair.py' ...

But it leads to the following error:

`Traceback (most recent call last):
  File "/usr/local/bin/mp", line 11, in <module>
    load_entry_point('MultiPlanarUNet==0.2.2', 'console_scripts', 'mp')()
  File "/usr/local/lib/python3.6/dist-packages/MultiPlanarUNet-0.2.2-py3.6.egg/MultiPlanarUNet/bin/mp.py", line 55, in entry_func
    mod.entry_func(parsed.args)
  File "/usr/local/lib/python3.6/dist-packages/MultiPlanarUNet-0.2.2-py3.6.egg/MultiPlanarUNet/bin/train.py", line 398, in entry_func
    raise e
  File "/usr/local/lib/python3.6/dist-packages/MultiPlanarUNet-0.2.2-py3.6.egg/MultiPlanarUNet/bin/train.py", line 394, in entry_func
    run(project_dir=project_dir, gpu_mon=gpu_mon, logger=logger, args=args)
  File "/usr/local/lib/python3.6/dist-packages/MultiPlanarUNet-0.2.2-py3.6.egg/MultiPlanarUNet/bin/train.py", line 331, in run
    args=args)
  File "/usr/local/lib/python3.6/dist-packages/MultiPlanarUNet-0.2.2-py3.6.egg/MultiPlanarUNet/bin/train.py", line 238, in get_data_sequences
    base_path=project_dir)
  File "/usr/local/lib/python3.6/dist-packages/MultiPlanarUNet-0.2.2-py3.6.egg/MultiPlanarUNet/preprocessing/data_preparation_funcs.py", line 176, in prepare_for_multi_view_unet
    is_validation=True, **hparams["fit"])
  File "/usr/local/lib/python3.6/dist-packages/MultiPlanarUNet-0.2.2-py3.6.egg/MultiPlanarUNet/image/image_pair_loader.py", line 432, in get_sequencer
    self.prepare_for_iso_live_views(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/MultiPlanarUNet-0.2.2-py3.6.egg/MultiPlanarUNet/image/image_pair_loader.py", line 381, in prepare_for_iso_live_views
    image.prepare_for_iso_live(bg_value, bg_class, scaler)
  File "/usr/local/lib/python3.6/dist-packages/MultiPlanarUNet-0.2.2-py3.6.egg/MultiPlanarUNet/image/image_pair.py", line 271, in prepare_for_iso_live
    bg_value = [np.percentile(self.image[..., i], bg_pct) for i in range(self.n_channels)]
  File "/usr/local/lib/python3.6/dist-packages/MultiPlanarUNet-0.2.2-py3.6.egg/MultiPlanarUNet/image/image_pair.py", line 271, in <listcomp>
    bg_value = [np.percentile(self.image[..., i], bg_pct) for i in range(self.n_channels)]
  File "/usr/local/lib/python3.6/dist-packages/MultiPlanarUNet-0.2.2-py3.6.egg/MultiPlanarUNet/image/image_pair.py", line 147, in image
    dtype=self.im_dtype)
  File "/usr/local/lib/python3.6/dist-packages/nibabel-2.5.1-py3.6.egg/nibabel/dataobj_images.py", line 348, in get_fdata
    data = np.asanyarray(self._dataobj).astype(dtype, copy=False)
  File "/home/akshay/.local/lib/python3.6/site-packages/numpy/core/_asarray.py", line 138, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
  File "/usr/local/lib/python3.6/dist-packages/nibabel-2.5.1-py3.6.egg/nibabel/arrayproxy.py", line 355, in __array__
    raw_data = self.get_unscaled()
  File "/usr/local/lib/python3.6/dist-packages/nibabel-2.5.1-py3.6.egg/nibabel/arrayproxy.py", line 350, in get_unscaled
    mmap=self._mmap)
  File "/usr/local/lib/python3.6/dist-packages/nibabel-2.5.1-py3.6.egg/nibabel/volumeutils.py", line 524, in array_from_file
    n_read = infile.readinto(data_bytes)
  File "/usr/lib/python3.6/gzip.py", line 276, in read
    return self._buffer.read(size)
MemoryError` 

What could be causing this? Moreover, running "nvidia-smi" shows no active GPU processes. Are there any other ways of checking whether MultiPlanarUNet is interacting with GPUs?

**Comment by perslev** [comment]
Hi,

The --force_GPU flag is used to set a specific GPU independent of whether it is already in use or not. E.g. if you want to use GPU with identifier '0' - no matter its current status - you would set --force GPU 0. In many cases you won't have to use the --force_GPU flag as an available GPU is automatically selected. However, if you have other applications using the GPU it can be necessary to set the --force_GPU flag.

The MemoryError seems to occur when loading your data. Maybe your dataset is too large to fit in your computers RAM. How large is the dataset and how much memory does your computer have?

Currently, MultiPlanarUNet loads all data into memory before training. There is no functionality for streaming data from disk. However, let me know if this would be of interest, then I might add it in the future.

Cheers,
Mathias

**Comment by perslev** [comment]
In order to test that the GPU is working you could run the training script with the --just_one flag to load only a single image for testing purposes.

**Comment by admshumar** [comment]
Hi Mathias,

According to "du -sh -- *", I have 53Gb of training and validation data. According to MPUNet's audit, this consumes a total of 120.784GiB of memory, which is definitely more than my 56Gb of system memory can handle. Streaming data of this magnitude would be a great feature.

As for GPUs, that was due to an incorrect TensorFlow installation. Thanks!

**Comment by perslev** [comment]
Hi,
I have added this feature request to the TODO list. I will unfortunately not have time myself to work on this until mid-late December. I hope you can wait until then :-)
