### ISSUE TITLE
When training on toy_data, TypeError: can only concatenate list (not "dict") to list

### ISSUE THREAD

**Issue by admshumar** [perslev/MultiPlanarUNet#7]
Running `mp train --just_one --overwrite` on a toy project with data generated using `mp toy_data --out_dir ./toy_data` leads to TensorFlow reporting a TypeError:

`Epoch 1/500
WARNING:tensorflow:From /home/akshay/.local/lib/python3.6/site-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
2019-11-12 14:46:01.034121: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-11-12 14:46:11.320775: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties:
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 2447:00:00.0
2019-11-12 14:46:11.320857: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-11-12 14:46:11.320885: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2019-11-12 14:46:11.320909: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2019-11-12 14:46:11.320932: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2019-11-12 14:46:11.320954: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2019-11-12 14:46:11.320976: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2019-11-12 14:46:11.321000: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-11-12 14:46:11.321705: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-11-12 14:46:11.323352: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties:
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 2447:00:00.0
2019-11-12 14:46:11.323398: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-11-12 14:46:11.323424: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2019-11-12 14:46:11.323446: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2019-11-12 14:46:11.323468: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2019-11-12 14:46:11.323490: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2019-11-12 14:46:11.323512: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2019-11-12 14:46:11.323534: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-11-12 14:46:11.324196: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-11-12 14:46:11.324233: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-11-12 14:46:11.324247: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0
2019-11-12 14:46:11.324255: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N
2019-11-12 14:46:11.324970: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10805 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 2447:00:00.0, compute capability: 3.7)
2019-11-12 14:46:11.325972: I tensorflow/core/profiler/lib/profiler_session.cc:174] Profiler session started.
2019-11-12 14:46:11.341159: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcupti.so.10.0
  1/157 [..............................] - ETA: 49:50 - loss: 0.49752019-11-12 14:46:13.153506: I tensorflow/core/platform/default/device_tracer.cc:641] Collecting 4204 kernel records, 123 memcpy records.
156/157 [============================>.] - ETA: 1s - loss: 0.2752can only concatenate list (not "dict") to list
Traceback (most recent call last):
  File "/usr/local/bin/mp", line 11, in <module>
    load_entry_point('MultiPlanarUNet==0.2.2', 'console_scripts', 'mp')()
  File "/usr/local/lib/python3.6/dist-packages/MultiPlanarUNet-0.2.2-py3.6.egg/MultiPlanarUNet/bin/mp.py", line 55, in entry_func
    mod.entry_func(parsed.args)
  File "/usr/local/lib/python3.6/dist-packages/MultiPlanarUNet-0.2.2-py3.6.egg/MultiPlanarUNet/bin/train.py", line 398, in entry_func
    raise e
  File "/usr/local/lib/python3.6/dist-packages/MultiPlanarUNet-0.2.2-py3.6.egg/MultiPlanarUNet/bin/train.py", line 394, in entry_func
    run(project_dir=project_dir, gpu_mon=gpu_mon, logger=logger, args=args)
  File "/usr/local/lib/python3.6/dist-packages/MultiPlanarUNet-0.2.2-py3.6.egg/MultiPlanarUNet/bin/train.py", line 358, in run
    hparams=hparams, no_im=args.no_images, **hparams["fit"])
  File "/usr/local/lib/python3.6/dist-packages/MultiPlanarUNet-0.2.2-py3.6.egg/MultiPlanarUNet/train/trainer.py", line 122, in fit
    raise e
  File "/usr/local/lib/python3.6/dist-packages/MultiPlanarUNet-0.2.2-py3.6.egg/MultiPlanarUNet/train/trainer.py", line 107, in fit
    val_ignore_class_zero)
  File "/usr/local/lib/python3.6/dist-packages/MultiPlanarUNet-0.2.2-py3.6.egg/MultiPlanarUNet/train/trainer.py", line 215, in _fit_loop
    self.model.fit_generator(**fit_kwargs)
  File "/home/akshay/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1433, in fit_generator
    steps_name='steps_per_epoch')
  File "/home/akshay/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_generator.py", line 331, in model_iteration
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/akshay/.local/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py", line 311, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/usr/local/lib/python3.6/dist-packages/MultiPlanarUNet-0.2.2-py3.6.egg/MultiPlanarUNet/callbacks/callbacks.py", line 416, in on_epoch_end
    TPs, relevant, selected, metrics = self.predict()
  File "/usr/local/lib/python3.6/dist-packages/MultiPlanarUNet-0.2.2-py3.6.egg/MultiPlanarUNet/callbacks/callbacks.py", line 318, in predict
    tensors = [self.model.total_loss] + metrics_tensors + self.model.outputs
TypeError: can only concatenate list (not "dict") to list`

I continued with `mp train_fusion`, under the assumption that the model was trained, but ran into an ImportError:
`Traceback (most recent call last):
  File "/usr/local/bin/mp", line 11, in <module>
    load_entry_point('MultiPlanarUNet==0.2.2', 'console_scripts', 'mp')()
  File "/usr/local/lib/python3.6/dist-packages/MultiPlanarUNet-0.2.2-py3.6.egg/MultiPlanarUNet/bin/mp.py", line 52, in entry_func
    mod = importlib.import_module("MultiPlanarUNet.bin." + script)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/dist-packages/MultiPlanarUNet-0.2.2-py3.6.egg/MultiPlanarUNet/bin/train_fusion.py", line 26, in <module>
    from MultiPlanarUNet.train import YAMLHParams
ImportError: cannot import name 'YAMLHParams'`

Ubuntu 18.04.3 LTS (GNU/Linux 5.0.0-1023-azure x86_64)
Cuda V10.0.130
CuDNN V7
tensorflow-gpu 1.14.0 (binary)
Nvidia Tesla K80 (12Gb)

**Comment by perslev** [comment]
Hi!

Could you please try and update to the latest version (0.2.4) with TensorFlow 2.0 or 2.1 and see if that works for you?
